Add activity tracking to entropy generator
fetchai/cosmos-consensus pull request #194
Opened 2020-10-02 08:51 UTC by jinmannwong

- Track the signature shares received from validators in a sliding window
- Slash when the number of shares in the window is below the allowed threshold 
- Do not double slash validators for inactivity in the same period

2020-10-02 10:00 UTC, n-hutton requested changes

2020-10-02 10:05 UTC, jinmannwong commented on beacon/entropy_generator.go
> +			entropyGenerator.Logger.Debug("Add evidence for inactivity", "height", entropy.Height, "validator", crypto.AddressHash(defAddress))
Sure thing. The slashing module actually does have Info logs when it jails a validator. Not sure why they weren't printing out on the tests.

2020-10-02 10:14 UTC, jinmannwong commented on beacon/entropy_generator.go
> +	activityTracking  map[uint]*list.List  // Record of validators
It is slightly nicer when iterating through the map as you can edit the list directly rather than having to access it by indexing into the map.

2020-10-02 10:30 UTC, n-hutton commented on beacon/entropy_generator.go
> +	activityTracking  map[uint]*list.List  // Record of validators
👍

2020-10-02 10:46 UTC, n-hutton commented on beacon/entropy_generator.go
> +			entropyGenerator.Logger.Debug("Add evidence for inactivity", "height", entropy.Height, "validator", crypto.AddressHash(defAddress))
Oh - perhaps I missed them. I guess the logs rather than being here could be in the SDK actually, since that would be when action actually happened

2020-10-05 08:41 UTC, jinmannwong commented on types/evidence.go
> +	// and evidence height is greater than aeon start
Evidence needs to be fully verified in Tendermint

2020-10-06 12:20 UTC, n-hutton approved these changes

2020-10-06 12:25 UTC, merged